name: icontrol
description: "Akıllı Evler için iControl"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mqtt_client: ^10.2.1

  flex_color_scheme: ^7.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/app/
    - assets/icons/rooms/
    - assets/icons/sensors/

  fonts:
    - family: Yellowtail
      fonts:
        - asset: assets/fonts/Yellowtail-Regular.ttf
